--liquibase formatted sql
-- Инициализация схемы БД в формате Liquibase formatted SQL.
-- (Файл заполнения данными — 002-seed-data.yaml — оставлен в YAML для наглядности обоих форматов.)

--changeset userbank:001-create-users
--comment: Таблица пользователей
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(500),
    date_of_birth DATE,
    password      VARCHAR(500) NOT NULL
);
--rollback DROP TABLE users;

--changeset userbank:001-create-account
--comment: Счёт пользователя (строго один на пользователя), баланс не может быть отрицательным
CREATE TABLE account (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL UNIQUE,
    balance         DECIMAL(19, 2) NOT NULL,
    -- первоначальный депозит — нужен, чтобы ограничить начисление 207% от него
    initial_balance DECIMAL(19, 2) NOT NULL,
    CONSTRAINT fk_account_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT chk_account_balance_non_negative CHECK (balance >= 0)
);
--rollback DROP TABLE account;

--changeset userbank:001-create-email-data
--comment: E-mail пользователя (у пользователя их может быть несколько, минимум один)
CREATE TABLE email_data (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    email   VARCHAR(200) NOT NULL UNIQUE,
    CONSTRAINT fk_email_user FOREIGN KEY (user_id) REFERENCES users (id)
);
--rollback DROP TABLE email_data;

--changeset userbank:001-create-phone-data
--comment: Телефон пользователя (у пользователя их может быть несколько, минимум один)
CREATE TABLE phone_data (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    phone   VARCHAR(13) NOT NULL UNIQUE,
    CONSTRAINT fk_phone_user FOREIGN KEY (user_id) REFERENCES users (id)
);
--rollback DROP TABLE phone_data;

--changeset userbank:001-indexes
--comment: Индексы под фильтры поиска и внешние ключи
CREATE INDEX idx_email_data_user_id ON email_data (user_id);
CREATE INDEX idx_phone_data_user_id ON phone_data (user_id);
CREATE INDEX idx_users_date_of_birth ON users (date_of_birth);
CREATE INDEX idx_users_name ON users (name);
--rollback DROP INDEX idx_email_data_user_id;
--rollback DROP INDEX idx_phone_data_user_id;
--rollback DROP INDEX idx_users_date_of_birth;
--rollback DROP INDEX idx_users_name;
